import { type Metadata } from 'next'
import {
  ClerkProvider,
} from '@clerk/nextjs'
import { Roboto } from 'next/font/google'
import './globals.css'

// Import Roboto with variable support
const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'], // Regular and Bold
  variable: '--font-roboto',
})

export const metadata: Metadata = {
  title: 'ESBL Prototype Demo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${roboto.variable} font-sans antialiased`}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
